# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['crypto'])


@router.get('/crypto/{symbol}', response_model=ContractDetailsList, tags=['crypto'])
async def get_crypto_contract(
    symbol: str, exchange: Optional[str] = None, currency: Optional[str] = None
) -> ContractDetailsList:
    return await impl.get_crypto_contract(symbol, exchange, currency)


@router.get('/crypto/{symbol}/rates', response_model=BarsResponse, tags=['crypto'])
async def get_crypto_rates(
    symbol: str,
    duration: str = ...,
    bar_size: Optional[str] = Query(None, alias='barSize'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
) -> BarsResponse:
    return await impl.get_crypto_rates(
        symbol,
        duration,
        bar_size,
        end_date_time,
        what_to_show,
        use_r_t_h,
        exchange,
        currency,
    )


@router.post(
    '/crypto/{symbol}/rates/ta', response_model=RatesTAResponse, tags=['crypto']
)
async def get_crypto_rates_t_a(
    symbol: str,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    body: RatesTARequest = ...,
) -> RatesTAResponse:
    return await impl.get_crypto_rates_t_a(symbol, exchange, currency, body)


@router.get('/crypto/{symbol}/tick', response_model=Ticker, tags=['crypto'])
async def get_crypto_tick(
    symbol: str, exchange: Optional[str] = None, currency: Optional[str] = None
) -> Ticker:
    return await impl.get_crypto_tick(symbol, exchange, currency)
