# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['forex'])


@router.get('/forex/{pair}', response_model=ContractDetailsList, tags=['forex'])
async def get_forex_contract(
    pair: str, exchange: Optional[str] = None
) -> ContractDetailsList:
    return await impl.get_forex_contract(pair, exchange)


@router.get('/forex/{pair}/rates', response_model=BarsResponse, tags=['forex'])
async def get_forex_rates(
    pair: str,
    duration: str = ...,
    bar_size: Optional[str] = Query(None, alias='barSize'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    exchange: Optional[str] = None,
) -> BarsResponse:
    return await impl.get_forex_rates(
        pair, duration, bar_size, end_date_time, what_to_show, use_r_t_h, exchange
    )


@router.post('/forex/{pair}/rates/ta', response_model=RatesTAResponse, tags=['forex'])
async def get_forex_rates_t_a(
    pair: str, exchange: Optional[str] = None, body: RatesTARequest = ...
) -> RatesTAResponse:
    return await impl.get_forex_rates_t_a(pair, exchange, body)


@router.get('/forex/{pair}/tick', response_model=Ticker, tags=['forex'])
async def get_forex_tick(pair: str, exchange: Optional[str] = None) -> Ticker:
    return await impl.get_forex_tick(pair, exchange)
