# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T22:08:14+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['futures'])


@router.get(
    '/futures/{symbol}',
    response_model=ContractDetailsList,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def get_future_contract(
    symbol: str,
    expiry: str = ...,
    exchange: str = ...,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
    refresh: Optional[bool] = False,
) -> Union[ContractDetailsList, ErrorEnvelope]:
    return await impl.get_future_contract(
        symbol, expiry, exchange, currency, multiplier, trading_class, refresh
    )


@router.get(
    '/futures/{symbol}/continuous',
    response_model=ContractDetailsList,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def get_continuous_future(
    symbol: str,
    exchange: str = ...,
    currency: Optional[str] = None,
    refresh: Optional[bool] = False,
) -> Union[ContractDetailsList, ErrorEnvelope]:
    return await impl.get_continuous_future(symbol, exchange, currency, refresh)


@router.get(
    '/futures/{symbol}/contracts',
    response_model=ContractDetailsList,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def list_future_contracts(
    symbol: str,
    exchange: str = ...,
    currency: Optional[str] = None,
    include_expired: Optional[bool] = Query(False, alias='includeExpired'),
    refresh: Optional[bool] = False,
) -> Union[ContractDetailsList, ErrorEnvelope]:
    return await impl.list_future_contracts(
        symbol, exchange, currency, include_expired, refresh
    )


@router.get(
    '/futures/{symbol}/rates',
    response_model=BarsResponse,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def get_future_rates(
    symbol: str,
    duration: str = ...,
    expiry: str = ...,
    exchange: str = ...,
    bar_size: Optional[str] = Query(None, alias='barSize'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
    refresh: Optional[bool] = False,
) -> Union[BarsResponse, ErrorEnvelope]:
    return await impl.get_future_rates(
        symbol,
        duration,
        expiry,
        exchange,
        bar_size,
        end_date_time,
        what_to_show,
        use_r_t_h,
        currency,
        multiplier,
        trading_class,
        refresh,
    )


@router.post(
    '/futures/{symbol}/rates/ta',
    response_model=RatesTAResponse,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def get_future_rates_t_a(
    symbol: str,
    expiry: str = ...,
    exchange: str = ...,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
    refresh: Optional[bool] = False,
    body: RatesTARequest = ...,
) -> Union[RatesTAResponse, ErrorEnvelope]:
    return await impl.get_future_rates_t_a(
        symbol, expiry, exchange, currency, multiplier, trading_class, refresh, body
    )


@router.get(
    '/futures/{symbol}/tick',
    response_model=Ticker,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['futures'],
)
async def get_future_tick(
    symbol: str,
    expiry: str = ...,
    exchange: str = ...,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
) -> Union[Ticker, ErrorEnvelope]:
    return await impl.get_future_tick(
        symbol, expiry, exchange, currency, multiplier, trading_class
    )
