# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['history'])


@router.get(
    '/history/completed_orders',
    response_model=CompletedOrdersResponse,
    tags=['history'],
)
async def get_completed_orders(
    api_only: Optional[bool] = Query(False, alias='apiOnly')
) -> CompletedOrdersResponse:
    return await impl.get_completed_orders(api_only)


@router.get('/history/executions', response_model=ExecutionsResponse, tags=['history'])
async def get_executions(
    account: Optional[str] = None,
    client_id: Optional[int] = Query(None, alias='clientId'),
    sec_type: Optional[str] = Query(None, alias='secType'),
    symbol: Optional[str] = None,
    exchange: Optional[str] = None,
    side: Optional[str] = None,
    time_after: Optional[str] = Query(None, alias='timeAfter'),
) -> ExecutionsResponse:
    return await impl.get_executions(
        account, client_id, sec_type, symbol, exchange, side, time_after
    )
