# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['options'])


@router.post(
    '/options/combo',
    response_model=Trade,
    responses={'400': {'model': ErrorEnvelope}},
    tags=['options'],
)
async def place_option_combo(body: ComboOrderRequest) -> Union[Trade, ErrorEnvelope]:
    return await impl.place_option_combo(body)


@router.post(
    '/options/exercise',
    response_model=ExerciseResponse,
    responses={'404': {'model': ErrorEnvelope}},
    tags=['options'],
)
async def exercise_option(
    body: ExerciseRequest,
) -> Union[ExerciseResponse, ErrorEnvelope]:
    return await impl.exercise_option(body)


@router.get('/options/{symbol}', response_model=ContractDetailsList, tags=['options'])
async def get_option_contract(
    symbol: str,
    expiry: str = ...,
    strike: float = ...,
    right: str = ...,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
) -> ContractDetailsList:
    return await impl.get_option_contract(
        symbol, expiry, strike, right, exchange, currency, multiplier, trading_class
    )


@router.get(
    '/options/{symbol}/chain',
    response_model=OptionChain,
    responses={'404': {'model': ErrorEnvelope}},
    tags=['options'],
)
async def get_option_chain(
    symbol: str,
    underlying_sec_type: Optional[str] = Query('STK', alias='underlyingSecType'),
    fut_fop_exchange: Optional[str] = Query('', alias='futFopExchange'),
    underlying_con_id: Optional[int] = Query(None, alias='underlyingConId'),
) -> Union[OptionChain, ErrorEnvelope]:
    return await impl.get_option_chain(
        symbol, underlying_sec_type, fut_fop_exchange, underlying_con_id
    )


@router.get('/options/{symbol}/rates', response_model=BarsResponse, tags=['options'])
async def get_option_rates(
    symbol: str,
    expiry: str = ...,
    strike: float = ...,
    right: str = ...,
    duration: str = ...,
    bar_size: Optional[str] = Query(None, alias='barSize'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
) -> BarsResponse:
    return await impl.get_option_rates(
        symbol,
        expiry,
        strike,
        right,
        duration,
        bar_size,
        end_date_time,
        what_to_show,
        use_r_t_h,
        exchange,
        currency,
        multiplier,
        trading_class,
    )


@router.post(
    '/options/{symbol}/rates/ta', response_model=RatesTAResponse, tags=['options']
)
async def get_option_rates_t_a(
    symbol: str,
    expiry: str = ...,
    strike: float = ...,
    right: str = ...,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
    body: RatesTARequest = ...,
) -> RatesTAResponse:
    return await impl.get_option_rates_t_a(
        symbol,
        expiry,
        strike,
        right,
        exchange,
        currency,
        multiplier,
        trading_class,
        body,
    )


@router.get('/options/{symbol}/tick', response_model=Ticker, tags=['options'])
async def get_option_tick(
    symbol: str,
    expiry: str = ...,
    strike: float = ...,
    right: str = ...,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    multiplier: Optional[str] = None,
    trading_class: Optional[str] = Query(None, alias='tradingClass'),
) -> Ticker:
    return await impl.get_option_tick(
        symbol, expiry, strike, right, exchange, currency, multiplier, trading_class
    )
