# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T22:08:14+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['orders'])


@router.get('/orders', response_model=TradesList, tags=['orders'])
async def list_orders() -> TradesList:
    return await impl.list_orders()


@router.post(
    '/orders',
    response_model=Trade,
    responses={
        '400': {'model': ErrorEnvelope},
        '404': {'model': ErrorEnvelope},
        '429': {'model': ErrorEnvelope},
    },
    tags=['orders'],
)
async def place_order(body: OrderRequest) -> Union[Trade, ErrorEnvelope]:
    return await impl.place_order(body)


@router.delete(
    '/orders',
    response_model=CancelAllResponse,
    responses={'429': {'model': ErrorEnvelope}},
    tags=['orders'],
)
async def cancel_all_orders() -> Union[CancelAllResponse, ErrorEnvelope]:
    return await impl.cancel_all_orders()


@router.get(
    '/orders/{orderId}',
    response_model=Trade,
    responses={'404': {'model': ErrorEnvelope}, '429': {'model': ErrorEnvelope}},
    tags=['orders'],
)
async def get_order(
    order_id: int = Path(..., alias='orderId')
) -> Union[Trade, ErrorEnvelope]:
    return await impl.get_order(order_id)


@router.delete(
    '/orders/{orderId}',
    response_model=CancelOrderResponse,
    responses={'404': {'model': ErrorEnvelope}, '429': {'model': ErrorEnvelope}},
    tags=['orders'],
)
async def cancel_order(
    order_id: int = Path(..., alias='orderId')
) -> Union[CancelOrderResponse, ErrorEnvelope]:
    return await impl.cancel_order(order_id)
