# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['stocks'])


@router.get(
    '/stocks/{symbol}',
    response_model=ContractDetailsList,
    responses={'404': {'model': ErrorEnvelope}},
    tags=['stocks'],
)
async def get_stock_contract(
    symbol: str,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    primary_exchange: Optional[str] = Query(None, alias='primaryExchange'),
) -> Union[ContractDetailsList, ErrorEnvelope]:
    return await impl.get_stock_contract(symbol, exchange, currency, primary_exchange)


@router.get('/stocks/{symbol}/rates', response_model=BarsResponse, tags=['stocks'])
async def get_stock_rates(
    symbol: str,
    duration: str = ...,
    bar_size: Optional[str] = Query(None, alias='barSize'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    primary_exchange: Optional[str] = Query(None, alias='primaryExchange'),
) -> BarsResponse:
    return await impl.get_stock_rates(
        symbol,
        duration,
        bar_size,
        end_date_time,
        what_to_show,
        use_r_t_h,
        exchange,
        currency,
        primary_exchange,
    )


@router.post(
    '/stocks/{symbol}/rates/ta',
    response_model=RatesTAResponse,
    responses={'503': {'model': ErrorEnvelope}},
    tags=['stocks'],
)
async def get_stock_rates_t_a(
    symbol: str,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    primary_exchange: Optional[str] = Query(None, alias='primaryExchange'),
    body: RatesTARequest = ...,
) -> Union[RatesTAResponse, ErrorEnvelope]:
    return await impl.get_stock_rates_t_a(
        symbol, exchange, currency, primary_exchange, body
    )


@router.get('/stocks/{symbol}/tick', response_model=Ticker, tags=['stocks'])
async def get_stock_tick(
    symbol: str,
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    primary_exchange: Optional[str] = Query(None, alias='primaryExchange'),
) -> Ticker:
    return await impl.get_stock_tick(symbol, exchange, currency, primary_exchange)


@router.get('/stocks/{symbol}/ticks', response_model=TicksResponse, tags=['stocks'])
async def get_stock_ticks(
    symbol: str,
    start_date_time: Optional[str] = Query(None, alias='startDateTime'),
    end_date_time: Optional[str] = Query(None, alias='endDateTime'),
    number_of_ticks: Optional[int] = Query(1000, alias='numberOfTicks'),
    what_to_show: Optional[str] = Query(None, alias='whatToShow'),
    use_r_t_h: Optional[bool] = Query(False, alias='useRTH'),
    exchange: Optional[str] = None,
    currency: Optional[str] = None,
    primary_exchange: Optional[str] = Query(None, alias='primaryExchange'),
) -> TicksResponse:
    return await impl.get_stock_ticks(
        symbol,
        start_date_time,
        end_date_time,
        number_of_ticks,
        what_to_show,
        use_r_t_h,
        exchange,
        currency,
        primary_exchange,
    )
