# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T22:08:14+00:00

from __future__ import annotations

from fastapi import APIRouter

from ibkrapi.api import impl

from ..dependencies import *

router = APIRouter(tags=['system'])


@router.get(
    '/account',
    response_model=AccountSummary,
    responses={'404': {'model': ErrorEnvelope}},
    tags=['system'],
)
async def get_account_summary(
    account: Optional[str] = None,
) -> Union[AccountSummary, ErrorEnvelope]:
    return await impl.get_account_summary(account)


@router.get('/account/values', response_model=AccountSummary, tags=['system'])
async def get_account_values(account: Optional[str] = None) -> AccountSummary:
    return await impl.get_account_values(account)


@router.get('/accounts', response_model=AccountsList, tags=['system'])
async def list_accounts() -> AccountsList:
    return await impl.list_accounts()


@router.get('/ping', response_model=PingResponse, tags=['system'])
async def get_ping() -> PingResponse:
    return await impl.get_ping()


@router.get('/positions', response_model=PositionsList, tags=['system'])
async def list_positions(account: Optional[str] = None) -> PositionsList:
    return await impl.list_positions(account)
