# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T22:08:14+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import (
    cfd,
    crypto,
    forex,
    futures,
    history,
    options,
    orders,
    stocks,
    system,
)

app = FastAPI(
    title='ibkr-httpapi',
    description='HTTP wrapper over Interactive Brokers via ib_async + a Linux-native IB\nGateway container. Asset-class routed: /stocks, /options, /futures,\n/cfd, /forex, /crypto plus cross-cutting /orders, /positions,\n/account, /history.\n\nVersioning: Option B per ~/.claude/rule-details/designing-an-api.md —\npaths in this spec are unversioned; the runtime prefix `/v1` comes\nfrom `servers.url`. One spec per major version.\n',
    version='1.0.0',
    license={'name': 'WTFPL'},
    servers=[
        {'url': '/v1', 'description': "This deployment's v1 API. Prefix is fixed."}
    ],
)

app.include_router(cfd.router)
app.include_router(crypto.router)
app.include_router(forex.router)
app.include_router(futures.router)
app.include_router(history.router)
app.include_router(options.router)
app.include_router(orders.router)
app.include_router(stocks.router)
app.include_router(system.router)
from typing import Optional, Union

from fastapi import Path, Query

from .models import (
    AccountsList,
    AccountSummary,
    BarsResponse,
    CancelAllResponse,
    CancelOrderResponse,
    ComboOrderRequest,
    CompletedOrdersResponse,
    ContractDetailsList,
    ErrorEnvelope,
    ExecutionsResponse,
    ExerciseRequest,
    ExerciseResponse,
    OptionChain,
    OrderRequest,
    PingResponse,
    PositionsList,
    RatesTARequest,
    RatesTAResponse,
    Ticker,
    TicksResponse,
    Trade,
    TradesList,
)
