# generated by fastapi-codegen:
#   filename:  v1.yaml
#   timestamp: 2026-06-20T18:46:52+00:00

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class ErrorEnvelope(BaseModel):
    code: Annotated[
        str, Field(description='Stable UPPER_SNAKE_CASE machine-readable identifier.')
    ]
    message: str
    details: Optional[Dict[str, Any]] = None


class PingResponse(BaseModel):
    status: Annotated[str, Field(examples=['ok'])]
    connected: bool
    serverVersion: Optional[int] = None
    startTime: Optional[str] = None
    uptimeSeconds: Optional[float] = None
    msgsSent: Optional[int] = None
    msgsRecv: Optional[int] = None


class AccountsList(BaseModel):
    accounts: List[str]


class AccountSummaryEntry1(BaseModel):
    value: Optional[str] = None
    currency: Optional[str] = None
    modelCode: Optional[str] = None


class AccountSummaryEntry(RootModel[Dict[str, AccountSummaryEntry1]]):
    root: Dict[str, AccountSummaryEntry1]


class AccountSummary(BaseModel):
    accounts: Dict[str, AccountSummaryEntry]


class Contract(BaseModel):
    conid: int
    symbol: str
    secType: str
    exchange: str
    primaryExchange: Optional[str] = None
    currency: str
    lastTradeDateOrContractMonth: Optional[str] = None
    strike: Optional[float] = None
    right: Optional[str] = None
    multiplier: Optional[str] = None
    tradingClass: Optional[str] = None
    localSymbol: Optional[str] = None


class ContractDetails(BaseModel):
    contract: Contract
    marketName: Optional[str] = None
    minTick: Optional[float] = None
    orderTypes: Optional[List[str]] = None
    validExchanges: Optional[List[str]] = None
    priceMagnifier: Optional[int] = None
    longName: Optional[str] = None
    industry: Optional[str] = None
    category: Optional[str] = None
    subcategory: Optional[str] = None
    timeZoneId: Optional[str] = None
    tradingHours: Optional[str] = None
    liquidHours: Optional[str] = None
    evRule: Optional[str] = None
    evMultiplier: Optional[float] = None


class ContractDetailsList(BaseModel):
    contracts: List[ContractDetails]


class Greeks(BaseModel):
    delta: Optional[float] = None
    gamma: Optional[float] = None
    theta: Optional[float] = None
    vega: Optional[float] = None
    impliedVol: Optional[float] = None
    optPrice: Optional[float] = None
    undPrice: Optional[float] = None


class Ticker(BaseModel):
    contract: Contract
    time: Optional[str] = None
    bid: Optional[float] = None
    bidSize: Optional[float] = None
    ask: Optional[float] = None
    askSize: Optional[float] = None
    last: Optional[float] = None
    lastSize: Optional[float] = None
    close: Optional[float] = None
    open: Optional[float] = None
    high: Optional[float] = None
    low: Optional[float] = None
    volume: Optional[float] = None
    vwap: Optional[float] = None
    halted: Optional[float] = None
    modelGreeks: Optional[Greeks] = None
    bidGreeks: Optional[Greeks] = None
    askGreeks: Optional[Greeks] = None
    lastGreeks: Optional[Greeks] = None


class Bar(BaseModel):
    time: str
    open: float
    high: float
    low: float
    close: float
    volume: Optional[float] = None
    average: Optional[float] = None
    barCount: Optional[int] = None


class BarsResponse(BaseModel):
    symbol: Optional[str] = None
    pair: Optional[str] = None
    secType: Optional[str] = None
    expiry: Optional[str] = None
    strike: Optional[float] = None
    right: Optional[str] = None
    bars: List[Bar]


class Tick(BaseModel):
    time: str
    price: Optional[float] = None
    size: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None
    bidSize: Optional[float] = None
    askSize: Optional[float] = None


class TicksResponse(BaseModel):
    symbol: Optional[str] = None
    secType: Optional[str] = None
    ticks: List[Tick]


class RatesTARequest(BaseModel):
    duration: Annotated[
        str, Field(description="IBKR duration string (e.g. '30 D', '1 Y')")
    ]
    barSize: Optional[str] = None
    endDateTime: Optional[str] = None
    whatToShow: Optional[str] = None
    useRTH: Optional[bool] = False
    indicators: Optional[Dict[str, Any]] = None
    recentBars: Optional[int] = None


class RatesTAResponse(BaseModel):
    symbol: Optional[str] = None
    secType: Optional[str] = None
    bars: List[Bar]
    ta: Optional[Dict[str, Any]] = None
    asOf: Optional[str] = None


class OptionChainEntry(BaseModel):
    exchange: Optional[str] = None
    tradingClass: Optional[str] = None
    multiplier: Optional[str] = None
    expirations: Optional[List[str]] = None
    strikes: Optional[List[float]] = None


class OptionChain(BaseModel):
    symbol: str
    underlyingConId: Optional[int] = None
    chains: List[OptionChainEntry]


class OrderRequest(BaseModel):
    assetClass: Annotated[
        str, Field(description='stock / option / future / cfd / forex / crypto')
    ]
    symbol: str
    expiry: Optional[str] = None
    strike: Optional[float] = None
    right: Optional[str] = None
    exchange: Optional[str] = None
    currency: Optional[str] = None
    multiplier: Optional[str] = None
    tradingClass: Optional[str] = None
    primaryExchange: Optional[str] = None
    conid: Optional[int] = None
    action: Annotated[str, Field(description='BUY or SELL')]
    quantity: Annotated[float, Field(gt=0.0)]
    orderType: Optional[str] = 'MKT'
    lmtPrice: Optional[float] = None
    auxPrice: Optional[float] = None
    tif: Optional[str] = 'DAY'
    outsideRth: Optional[bool] = False
    transmit: Optional[bool] = True
    account: Optional[str] = None
    goodAfterTime: Optional[str] = None
    goodTillDate: Optional[str] = None
    ocaGroup: Optional[str] = None
    parentId: Optional[int] = None


class OrderStatus(BaseModel):
    status: Optional[str] = None
    filled: Optional[float] = None
    remaining: Optional[float] = None
    avgFillPrice: Optional[float] = None
    permId: Optional[int] = None
    lastFillPrice: Optional[float] = None
    whyHeld: Optional[str] = None
    mktCapPrice: Optional[float] = None


class Order(BaseModel):
    orderId: Optional[int] = None
    permId: Optional[int] = None
    clientId: Optional[int] = None
    action: Optional[str] = None
    totalQuantity: Optional[float] = None
    orderType: Optional[str] = None
    lmtPrice: Optional[float] = None
    auxPrice: Optional[float] = None
    tif: Optional[str] = None
    outsideRth: Optional[bool] = None
    transmit: Optional[bool] = None
    account: Optional[str] = None
    parentId: Optional[int] = None
    ocaGroup: Optional[str] = None
    goodAfterTime: Optional[str] = None
    goodTillDate: Optional[str] = None


class Trade(BaseModel):
    contract: Optional[Contract] = None
    order: Optional[Order] = None
    orderStatus: Optional[OrderStatus] = None
    fills: Optional[List[Dict[str, Any]]] = None
    log: Optional[List[Dict[str, Any]]] = None


class TradesList(BaseModel):
    trades: List[Trade]


class CancelOrderResponse(BaseModel):
    status: Annotated[Optional[str], Field(examples=['cancelling'])] = None
    orderId: Optional[int] = None


class CancelAllResponse(BaseModel):
    status: Annotated[Optional[str], Field(examples=['global_cancel_requested'])] = None


class ComboLegSpec(BaseModel):
    conid: int
    ratio: Optional[int] = 1
    action: Annotated[str, Field(description='BUY / SELL')]
    exchange: Optional[str] = 'SMART'


class ComboOrderRequest(BaseModel):
    symbol: str
    legs: List[ComboLegSpec]
    action: str
    quantity: int
    orderType: Optional[str] = 'LMT'
    lmtPrice: Optional[float] = None
    tif: Optional[str] = 'DAY'
    exchange: Optional[str] = 'SMART'
    currency: Optional[str] = 'USD'
    account: Optional[str] = None


class ExerciseRequest(BaseModel):
    conid: int
    action: Annotated[str, Field(description='EXERCISE or LAPSE')]
    quantity: Annotated[int, Field(ge=1)]
    account: str
    override: Optional[bool] = False


class ExerciseResponse(BaseModel):
    status: Optional[str] = None
    contract: Optional[Contract] = None
    action: Optional[str] = None


class Fill(BaseModel):
    contract: Optional[Contract] = None
    execution: Optional[Dict[str, Any]] = None
    commissionReport: Optional[Dict[str, Any]] = None
    time: Optional[str] = None


class ExecutionsResponse(BaseModel):
    fills: List[Fill]


class CompletedOrdersResponse(BaseModel):
    trades: List[Dict[str, Any]]


class Position(BaseModel):
    account: str
    contract: Contract
    position: float
    avgCost: float


class PositionsList(BaseModel):
    positions: List[Position]
